"""empty message

Revision ID: 07e0342bf2bc
Revises: bb1169616ff1
Create Date: 2017-11-20 13:41:12.685479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e0342bf2bc'
down_revision = 'bb1169616ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_member', sa.Column('d_date', sa.Date(), nullable=False))
    op.add_column('tbl_member', sa.Column('e_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_member', 'e_date')
    op.drop_column('tbl_member', 'd_date')
    # ### end Alembic commands ###
