"""empty message

Revision ID: 5203bdbc705e
Revises: e6b689c27d41
Create Date: 2017-11-20 13:27:49.344345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5203bdbc705e'
down_revision = 'e6b689c27d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_product', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_product', sa.Column('price', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
