"""empty message

Revision ID: 671d7e54cafb
Revises: 
Create Date: 2017-11-19 17:06:11.831829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671d7e54cafb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=True),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('uname', sa.String(length=100), nullable=True),
    sa.Column('pw', sa.String(length=100), nullable=True),
    sa.Column('addr', sa.String(length=100), nullable=True),
    sa.Column('ph', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ph'),
    sa.UniqueConstraint('uname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_admin')
    # ### end Alembic commands ###
