"""empty message

Revision ID: 6ebed60bde24
Revises: 671d7e54cafb
Create Date: 2017-11-19 22:18:36.736521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebed60bde24'
down_revision = '671d7e54cafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=False),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('addr', sa.String(length=100), nullable=True),
    sa.Column('ph', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'tbl_admin', 'fname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column(u'tbl_admin', 'pw',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column(u'tbl_admin', 'uname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'tbl_admin', 'uname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column(u'tbl_admin', 'pw',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column(u'tbl_admin', 'fname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('member')
    # ### end Alembic commands ###
