"""empty message

Revision ID: a5444c3a88a7
Revises: 5203bdbc705e
Create Date: 2017-11-20 13:28:21.484530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5444c3a88a7'
down_revision = '5203bdbc705e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_product', sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_product', 'price')
    # ### end Alembic commands ###
