"""empty message

Revision ID: a808c7ace855
Revises: 07e0342bf2bc
Create Date: 2017-11-20 20:59:55.772022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a808c7ace855'
down_revision = '07e0342bf2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('p_id', sa.Integer(), nullable=False),
    sa.Column('pro_qty', sa.Integer(), nullable=False),
    sa.Column('pro_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint(u'pro_qty >= 1', name='check_quantity_entered'),
    sa.ForeignKeyConstraint(['p_id'], ['tbl_product.id'], ),
    sa.ForeignKeyConstraint(['s_id'], ['tbl_supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    # ### end Alembic commands ###
