"""empty message

Revision ID: bb1169616ff1
Revises: a5444c3a88a7
Create Date: 2017-11-20 13:40:32.966594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb1169616ff1'
down_revision = 'a5444c3a88a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_member', 'd_date')
    op.drop_column('tbl_member', 'e_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_member', sa.Column('e_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tbl_member', sa.Column('d_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
