"""empty message

Revision ID: e6b689c27d41
Revises: 
Create Date: 2017-11-20 13:26:11.435060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b689c27d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=8, scale=2), nullable=True),
    sa.CheckConstraint(u'quantity >= 0', name='check_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('addr', sa.String(length=100), nullable=True),
    sa.Column('ph', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'tbl_member', sa.Column('d_date', sa.DateTime(), nullable=False))
    op.add_column(u'tbl_member', sa.Column('e_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tbl_member', 'e_date')
    op.drop_column(u'tbl_member', 'd_date')
    op.drop_table('tbl_supplier')
    op.drop_table('tbl_product')
    # ### end Alembic commands ###
