"""empty message

Revision ID: efaa83e50a76
Revises: 6ebed60bde24
Create Date: 2017-11-19 22:19:49.488383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaa83e50a76'
down_revision = '6ebed60bde24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=100), nullable=False),
    sa.Column('lname', sa.String(length=100), nullable=True),
    sa.Column('addr', sa.String(length=100), nullable=True),
    sa.Column('ph', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('addr', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ph', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'member_pkey')
    )
    op.drop_table('tbl_member')
    # ### end Alembic commands ###
